### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by SpeedRider** [flori-schwa/VarLightFabric#4] opened 2020-02-19 06:42 UTC
[crash-2020-02-19_14.36.08-server.txt](https://github.com/flori-schwa/VarLightFabric/files/4223498/crash-2020-02-19_14.36.08-server.txt)

**Comment by flori-schwa** [comment] 2020-02-19 08:33
Duplicate of #2 which was fixed in release 1.1.1

**Closed as completed** 2020-02-19 08:34 UTC
Labels: duplicate
